"use client"

import {
  type ComponentProps,
  createContext,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  useContext,
  useRef,
} from "react"

import { cn } from "@/lib/utils"

import { CopyButton } from "./copy-button"

export interface CodeBlockProps extends ComponentProps<"figure"> {
  Actions?: (props: { children?: ReactNode; className?: string; }) => ReactNode

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number

  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean

  titleProps?: HTMLAttributes<HTMLDivElement>

  viewportProps?: HTMLAttributes<HTMLElement>
}

const TabsContext = createContext<null | {
  containerRef: RefObject<HTMLDivElement | null>
  nested: boolean
}>(null)

export function CodeBlock({
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  allowCopy,
  children,
  icon,
  keepBackground = false,
  ref,
  title,
  titleProps = {},
  viewportProps = {},
  ...props
}: CodeBlockProps) {
  const isTab = useContext(TabsContext) !== null
  const areaRef = useRef<HTMLDivElement>(null)
  allowCopy ??= !isTab
  const bg = cn(
    "bg-muted",
    keepBackground &&
      `
        bg-(--shiki-light-bg)
        dark:bg-(--shiki-dark-bg)
      `
  )

  return (
    <figure
      dir="ltr"
      ref={ref}
      {...props}
      className={cn(
        isTab ? [bg, "rounded-lg shadow-sm"] : "my-4 rounded-xl bg-card p-1",
        "shiki not-prose relative overflow-hidden border text-sm outline-none",
        props.className
      )}
    >
      {title ? (
        <div
          {...titleProps}
          className={cn(
            "flex h-9.5 items-center gap-2 ps-3 text-muted-foreground",
            isTab && "border-b",
            titleProps.className
          )}
        >
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            <div className="[&_svg]:size-3.5">{icon}</div>
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            children: allowCopy && (
              <CopyButton containerRef={areaRef as RefObject<HTMLElement>} />
            ),
          })}
        </div>
      ) : (
        Actions({
          children: allowCopy && (
            <CopyButton containerRef={areaRef as RefObject<HTMLElement>} />
          ),
          className:
            "absolute top-1 right-1 z-2 bg-card rounded-bl-lg border-l border-b text-muted-foreground",
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        className={cn(
          !isTab && [bg, "rounded-lg"],
          "fd-scroll-container max-h-[calc(530px-44px)] overflow-auto py-3.5 text-[13px]",
          viewportProps.className
        )}
        style={
          {
            "--padding-right": !title ? "calc(var(--spacing) * 8)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        {children}
      </div>
    </figure>
  )
}
