reviews:
  enabled: true

  guidelines:
    - path: ".github/copilot-instructions.md"
      description: "Limeplay project guidelines, architecture patterns, and code review checklist"

  paths:
    include:
      - "apps/www/registry/**"
      - "apps/www/content/docs/**"
    exclude:
      - "**/node_modules/**"
      - "**/out/**"
      - "**/.next/**"

  tools:
    eslint:
      enabled: true
