# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

reviews:
  path_filters:
    - "apps/www/registry/**"
    - "apps/www/content/docs/**"
    - "!**/node_modules/**"
    - "!**/out/**"
    - "!**/.next/**"

knowledge_base:
  code_guidelines:
    enabled: true
    file_patterns:
      - "prompts/code-rabbit.md"

tools:
  eslint:
    enabled: true
