/**
 * registry-dev.mts
 *
 * Single-file registry build pipeline:
 *   1. Compile  → registry.json, registry-pro.json, registry/__index__.tsx
 *   2. shadcn build → public/r/ (free) and registry/.generated/pro/ (pro)
 *   3. Copy free → public/r/free/
 *   4. validate-registries.ts
 *
 * Flags:
 *   --watch   Re-run on file changes in registry/collection/ and registry/default/
 *
 * Usage:
 *   REGISTRY_HOST=http://localhost:3000 bun --watch run ./scripts/registry-dev.mts --watch
 *   REGISTRY_HOST=https://limeplay.winoffrg.dev bun run ./scripts/registry-dev.mts
 */

import { type ChildProcess, exec } from "child_process"
import { promises as fs, statSync, watch } from "fs"
import path from "path"
import { rimraf } from "rimraf"
import { type Registry } from "shadcn/schema"

// Dynamic import to avoid ESM named-export resolution issues with .mts + tsx
const { registry } = await import("@/registry/collection/index")

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const WATCH = process.argv.includes("--watch")
const CWD = process.cwd()

const STYLE = "default"
const PRO_STYLE = "pro"
const REGISTRY_HOST = process.env.REGISTRY_HOST ?? "http://localhost:3000"
const BASE_URL = `${REGISTRY_HOST}/r`
const LIMEPLAY_REGISTRY_NAME = "@limeplay"
const PUBLIC_OUTPUT_DIR = path.join(CWD, "public/r")
const PRO_OUTPUT_DIR = path.join(CWD, "registry/.generated/pro")
const PRO_RUNTIME_MODULE = path.join(CWD, "registry/__pro__.ts")
const PUBLIC_PRO_OUTPUT_DIR = path.join(CWD, "public/r/pro")

// ---------------------------------------------------------------------------
// Maps
// ---------------------------------------------------------------------------

const registryItems = registry.items
const registryItemsMap = new Map<string, Registry["items"][number]>()
for (const item of registryItems) {
  registryItemsMap.set(item.name, item)
}

const isProItem = (item: Registry["items"][number]) =>
  item.categories?.includes("pro")

// ---------------------------------------------------------------------------
// Path mappings – auto-generate `target` for block files that lack one
// ---------------------------------------------------------------------------

const PATH_MAPPINGS = [
  {
    pattern: "blocks/",
    targetFn: (filePath: string) => {
      const match = /blocks\/([^/]+)\/(.+)/.exec(filePath)
      if (match) {
        const [, blockName, rest] = match
        return `components/${blockName}/${rest}`
      }
      return null
    },
  },
]

// ---------------------------------------------------------------------------
// Resolve registry dependencies to full URLs
// ---------------------------------------------------------------------------

async function buildRegistryIndex(
  registries: Array<{ registry: Registry; style: string }>
) {
  console.log(
    `Building registry/__index__.tsx with ${registries.length} tier(s)...`
  )

  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/registry-dev.mts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`

  for (const { registry: reg, style } of registries) {
    index += `\n  "${style}": {`

    for (const item of reg.items) {
      if (!item.files?.length) {
        index += `
    "${item.name}": {
      name: "${item.name}",
      description: "${item.description ?? ""}",
      type: "${item.type}",
      registryDependencies: ${JSON.stringify(item.registryDependencies)},
      files: [],
      component: null,
      meta: ${JSON.stringify(item.meta)},
    },`
        continue
      }

      const componentPath = `@/registry/${style}/${
        typeof item.files[0] === "string" ? item.files[0] : item.files[0].path
      }`

      const filesStr = item.files
        .map((file) => {
          if (typeof file === "string") {
            const fp = `registry/${style}/${file}`
            return `"${path.resolve(fp)}"`
          }
          const fp = `registry/${style}/${file.path}`
          return `{
        path: "${fp}",
        type: "${file.type}",
        target: "${file.target ?? ""}"
      }`
        })
        .join(",")

      index += `
    "${item.name}": {
      name: "${item.name}",
      categories: ${JSON.stringify(item.categories)},
      description: "${item.description ?? ""}",
      type: "${item.type}",
      registryDependencies: ${JSON.stringify(item.registryDependencies)},
      files: [${filesStr}],
      component: React.lazy(async () => {
        const mod = await import("${componentPath}")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
        return { default: mod.default || mod[exportName] }
      }),
      meta: ${JSON.stringify(item.meta)},
      title: ${JSON.stringify(item.title)},
    },`
    }

    index += `\n  },`
  }

  index += `\n}\n`

  const dest = path.join(CWD, "registry", "__index__.tsx")
  await fs.mkdir(path.dirname(dest), { recursive: true })
  rimraf.sync(dest)
  await fs.writeFile(dest, index)
}

// ---------------------------------------------------------------------------
// Process items – resolve deps + auto-fill targets
// ---------------------------------------------------------------------------

async function compile() {
  console.log(`Using registry host: ${REGISTRY_HOST}`)

  const hasProRegistry = await proRegistryExists()
  const proRegistryJsonPath = path.join(CWD, "registry-pro.json")

  // Split items by tier
  const freeItems = registryItems.filter((item) => !isProItem(item))
  const proItems = registryItems.filter((item) => {
    if (!isProItem(item)) return false
    const firstFile = item.files?.[0]
    if (!firstFile) return false
    const filePath = typeof firstFile === "string" ? firstFile : firstFile.path
    const pathParts = filePath.split("/")
    let itemDir: string
    if (pathParts[0] === "blocks" && pathParts.length > 1) {
      itemDir = path.join(CWD, "registry/pro", pathParts[0], pathParts[1])
    } else {
      itemDir = path.join(CWD, "registry/pro", pathParts[0])
    }
    try {
      return statSync(itemDir).isDirectory()
    } catch {
      return false
    }
  })

  // Free registry (the "index" style entry is already in the collection)
  const freeRegistry = createRegistry(freeItems)
  await writeRegistryJson(freeRegistry, STYLE, "registry.json")

  const registriesToIndex = [{ registry: freeRegistry, style: STYLE }]

  // Pro registry
  if (proItems.length > 0 && hasProRegistry) {
    console.log("Building pro registry...")
    const proRegistry = createRegistry(proItems, "winoffrg/limeplay-pro")
    await writeRegistryJson(proRegistry, PRO_STYLE, "registry-pro.json")
    registriesToIndex.push({ registry: proRegistry, style: PRO_STYLE })
  } else if (proItems.length > 0) {
    console.log("Pro items defined but submodule missing – skipping pro build")
    rimraf.sync(proRegistryJsonPath)
  } else {
    console.log("No pro items defined")
    rimraf.sync(proRegistryJsonPath)
  }

  await buildRegistryIndex(registriesToIndex)
  console.log("Compile complete!")
}

// ---------------------------------------------------------------------------
// Create a Registry object from processed items
// ---------------------------------------------------------------------------

async function copyFreeToExplicitDir() {
  const srcDir = PUBLIC_OUTPUT_DIR
  const destDir = path.join(CWD, "public/r/free")
  await fs.mkdir(destDir, { recursive: true })

  const entries = await fs.readdir(srcDir)
  for (const entry of entries) {
    if (!entry.endsWith(".json")) continue
    const srcPath = path.join(srcDir, entry)
    const stat = await fs.stat(srcPath)
    if (stat.isFile()) {
      await fs.copyFile(srcPath, path.join(destDir, entry))
    }
  }
  console.log("Copied free components to /r/free/")
}

// ---------------------------------------------------------------------------
// Write registry JSON (with style-prefixed paths for shadcn build)
// ---------------------------------------------------------------------------

function createRegistry(
  items: Registry["items"],
  name = "winoffrg/limeplay"
): Registry {
  return {
    homepage: "https://limeplay.winoffrg.dev",
    items: processItems(items),
    name,
  }
}

// ---------------------------------------------------------------------------
// Build registry/__index__.tsx (React.lazy component lookup for docs site)
// ---------------------------------------------------------------------------

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.stat(filePath)
    return true
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Pro registry detection
// ---------------------------------------------------------------------------

async function pipeline() {
  const start = Date.now()
  console.log("\n--- Registry build started ---\n")

  // 1. Compile registry.json, registry-pro.json, __index__.tsx
  await compile()

  // 2. shadcn build (free)
  rimraf.sync(PUBLIC_OUTPUT_DIR)
  await run("bun x shadcn build registry.json --output public/r")

  // 3. Copy free → /r/free/
  await copyFreeToExplicitDir()

  // 4. shadcn build (pro) – only if registry-pro.json was generated
  if (await pathExists(path.join(CWD, "registry-pro.json"))) {
    rimraf.sync(PUBLIC_PRO_OUTPUT_DIR)
    rimraf.sync(PRO_OUTPUT_DIR)
    await run(
      "bun x shadcn build registry-pro.json --output registry/.generated/pro"
    )
    await writeProRuntimeModule(PRO_OUTPUT_DIR)
  } else {
    rimraf.sync(PUBLIC_PRO_OUTPUT_DIR)
    rimraf.sync(PRO_OUTPUT_DIR)
    await writeProRuntimeModule()
  }

  // 5. Validate
  await run("bun run ./scripts/validate-registries.ts")

  const elapsed = ((Date.now() - start) / 1000).toFixed(1)
  console.log(`\n--- Registry build complete (${elapsed}s) ---\n`)
}

// ---------------------------------------------------------------------------
// Shell helper
// ---------------------------------------------------------------------------

function processItems(items: Registry["items"]): Registry["items"] {
  return items.map((item) => {
    if (item.registryDependencies?.length) {
      item.registryDependencies = item.registryDependencies.map(
        resolveRegistryDependency
      )
    }

    if (item.files) {
      item.files = item.files.map((file) => {
        if (typeof file === "string") return file
        if (file.target) return file

        for (const mapping of PATH_MAPPINGS) {
          if (file.path.includes(mapping.pattern)) {
            const target = mapping.targetFn(file.path)
            if (target) return { ...file, target }
          }
        }
        return file
      })
    }

    return item
  })
}

async function proRegistryExists(): Promise<boolean> {
  try {
    const proPath = path.join(CWD, "registry/pro")
    const stat = await fs.stat(proPath)
    if (!stat.isDirectory()) return false
    const files = await fs.readdir(proPath, { recursive: true })
    return files.some(
      (f) => typeof f === "string" && (f.endsWith(".tsx") || f.endsWith(".ts"))
    )
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Copy free output to /r/free/
// ---------------------------------------------------------------------------

function resolveRegistryDependency(dependency: string): string {
  if (typeof dependency !== "string" || dependency.startsWith("http")) {
    return dependency
  }
  if (registryItemsMap.has(dependency)) {
    const item = registryItemsMap.get(dependency)!
    if (isProItem(item)) {
      return `${LIMEPLAY_REGISTRY_NAME}/pro/${dependency}`
    }
    return `${BASE_URL}/${dependency}.json`
  }
  return dependency
}

function run(cmd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc: ChildProcess = exec(cmd, { cwd: CWD })
    proc.stdout?.pipe(process.stdout)
    proc.stderr?.pipe(process.stderr)
    proc.on("exit", (code) => {
      if (code === 0) resolve()
      else reject(new Error(`Command failed (exit ${code}): ${cmd}`))
    })
  })
}

function startWatcher() {
  const dirs = [
    path.join(CWD, "registry/collection"),
    path.join(CWD, "registry/default"),
    path.join(CWD, "registry/pro"),
  ]

  let debounce: null | ReturnType<typeof setTimeout> = null
  let running = false

  const rebuild = () => {
    if (running) return
    running = true
    pipeline()
      .catch((err) => console.error("Build failed:", err.message))
      .finally(() => {
        running = false
      })
  }

  for (const dir of dirs) {
    try {
      watch(dir, { recursive: true }, (_event, filename) => {
        if (!filename) return
        if (
          !filename.endsWith(".ts") &&
          !filename.endsWith(".tsx") &&
          !filename.endsWith(".css")
        )
          return

        if (debounce) clearTimeout(debounce)
        debounce = setTimeout(rebuild, 300)
      })
      console.log(`Watching: ${path.relative(CWD, dir)}/`)
    } catch {
      // Directory may not exist (e.g. registry/pro without submodule)
    }
  }
}

// ---------------------------------------------------------------------------
// Compile step
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Full pipeline
// ---------------------------------------------------------------------------

async function writeProRuntimeModule(outputDir?: string) {
  const items: Record<string, unknown> = {}

  if (outputDir) {
    const entries = await fs.readdir(outputDir)
    for (const entry of entries) {
      if (!entry.endsWith(".json")) continue

      const filePath = path.join(outputDir, entry)
      const stat = await fs.stat(filePath)
      if (!stat.isFile()) continue

      const key = entry.replace(/\.json$/, "")
      items[key] = JSON.parse(await fs.readFile(filePath, "utf-8"))
    }
  }

  const moduleSource = `/* eslint-disable */
// This file is autogenerated by scripts/registry-dev.mts
// Do not edit this file directly.

export const proRegistryItems: Record<string, unknown> = ${JSON.stringify(
    items,
    null,
    2
  )}
`

  await fs.mkdir(path.dirname(PRO_RUNTIME_MODULE), { recursive: true })
  rimraf.sync(PRO_RUNTIME_MODULE)
  await fs.writeFile(PRO_RUNTIME_MODULE, moduleSource)
}

// ---------------------------------------------------------------------------
// Watch mode
// ---------------------------------------------------------------------------

async function writeRegistryJson(
  reg: Registry,
  style: string,
  fileName: string
) {
  console.log(`Writing ${fileName}...`)

  const output = {
    ...reg,
    items: reg.items.map((item) => ({
      ...item,
      files: item.files?.map((file) =>
        typeof file === "string"
          ? file
          : { ...file, path: `registry/${style}/${file.path}` }
      ),
    })),
  }

  const dest = path.join(CWD, fileName)
  rimraf.sync(dest)
  await fs.writeFile(dest, JSON.stringify(output, null, 2))
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

pipeline()
  .then(() => {
    if (WATCH) {
      startWatcher()
      console.log("Watching for changes... (Ctrl+C to stop)\n")
    }
  })
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
