// registry/__index__.tsx is auto-generated by registry:build and gitignored.
// This declaration prevents tsc errors when the file hasn't been generated yet.

declare module "@/registry/__index__" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const Index: Record<string, Record<string, any>>
}
