/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

"use client"

import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["http://localhost:3000/r/styles/default/utils.json"],
      files: [],
      component: null,
      meta: undefined,
    },
    "fallback-poster": {
      name: "fallback-poster",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/fallback-poster.tsx",
        type: "registry:ui",
        target: "components/player/fallback-poster.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/fallback-poster.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "fallback-poster"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "mute-control": {
      name: "mute-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/use-volume.json"],
      files: [{
        path: "registry/default/ui/mute-control.tsx",
        type: "registry:ui",
        target: "components/player/mute-control.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/mute-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "mute-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "media-provider": {
      name: "media-provider",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/create-media-store.json","http://localhost:3000/r/styles/default/use-media-state.json","http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/use-timeline.json","http://localhost:3000/r/styles/default/use-volume.json"],
      files: [{
        path: "registry/default/ui/media-provider.tsx",
        type: "registry:ui",
        target: "components/player/media-provider.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/media-provider.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "media-provider"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-layout": {
      name: "player-layout",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/use-player-root-store.json"],
      files: [{
        path: "registry/default/ui/player-layout.tsx",
        type: "registry:ui",
        target: "components/player/player-layout.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/player-layout.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-layout"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "media": {
      name: "media",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/media.tsx",
        type: "registry:ui",
        target: "components/player/media.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/media.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "media"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-control": {
      name: "volume-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/use-volume.json","http://localhost:3000/r/styles/default/use-track-events.json"],
      files: [{
        path: "registry/default/ui/volume-control.tsx",
        type: "registry:ui",
        target: "components/player/volume-control.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/volume-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "playback-control": {
      name: "playback-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-media-state.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/playback-control.tsx",
        type: "registry:ui",
        target: "components/player/playback-control.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/playback-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "playback-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "timeline-labels": {
      name: "timeline-labels",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/time.json"],
      files: [{
        path: "registry/default/ui/timeline-labels.tsx",
        type: "registry:ui",
        target: "components/player/timeline-labels.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/timeline-labels.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timeline-labels"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-hooks": {
      name: "player-hooks",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-shaka-player.json"],
      files: [{
        path: "registry/default/ui/player-hooks.tsx",
        type: "registry:ui",
        target: "components/player/player-hooks.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/player-hooks.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-hooks"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "timeline-control": {
      name: "timeline-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/use-timeline.json","http://localhost:3000/r/styles/default/use-track-events.json"],
      files: [{
        path: "registry/default/ui/timeline-control.tsx",
        type: "registry:ui",
        target: "components/player/timeline-control.tsx"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/timeline-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timeline-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "limeplay-logo": {
      name: "limeplay-logo",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/limeplay-logo.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/limeplay-logo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "limeplay-logo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/utils.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "create-media-store": {
      name: "create-media-store",
      description: "",
      type: "registry:lib",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json"],
      files: [{
        path: "registry/default/lib/create-media-store.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/create-media-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "create-media-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "time": {
      name: "time",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/time.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/time.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "time"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-player-root-store": {
      name: "use-player-root-store",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-player-root-store.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-player-root-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-player-root-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-volume": {
      name: "use-volume",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-volume.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-volume.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-volume"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-track-events": {
      name: "use-track-events",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-track-events.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-track-events.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-track-events"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-timeline": {
      name: "use-timeline",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/use-interval.json"],
      files: [{
        path: "registry/default/hooks/use-timeline.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-timeline.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-timeline"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-media-state": {
      name: "use-media-state",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-media-state.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-media-state.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-media-state"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-shaka-player": {
      name: "use-shaka-player",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-shaka-player.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-shaka-player.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-shaka-player"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-interval": {
      name: "use-interval",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-interval.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-interval.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-interval"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "custom-demo-controls": {
      name: "custom-demo-controls",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/internal/custom-demo-controls.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/internal/custom-demo-controls.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "custom-demo-controls"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-hooks-demo": {
      name: "player-hooks-demo",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-media-state.json","http://localhost:3000/r/styles/default/use-shaka-player.json","http://localhost:3000/r/styles/default/use-timeline.json","http://localhost:3000/r/styles/default/use-volume.json"],
      files: [{
        path: "registry/default/internal/player-hooks-demo.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/internal/player-hooks-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-hooks-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-root-demo": {
      name: "player-root-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/player-layout.json","http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/media.json","http://localhost:3000/r/styles/default/custom-demo-controls.json","http://localhost:3000/r/styles/default/player-hooks-demo.json","http://localhost:3000/r/styles/default/limeplay-logo.json","http://localhost:3000/r/styles/default/fallback-poster.json"],
      files: [{
        path: "registry/default/examples/player-root-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/player-root-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-root-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "fallback-poster-demo": {
      name: "fallback-poster-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/fallback-poster.json"],
      files: [{
        path: "registry/default/examples/fallback-poster-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/fallback-poster-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "fallback-poster-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "playback-state-control-demo": {
      name: "playback-state-control-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/playback-control.json"],
      files: [{
        path: "registry/default/examples/playback-state-control-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/playback-state-control-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "playback-state-control-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-horizontal-demo": {
      name: "volume-slider-control-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/volume-control.json","http://localhost:3000/r/styles/default/volume-state-control-demo.json"],
      files: [{
        path: "registry/default/examples/volume-slider-control-horizontal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-horizontal-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-horizontal-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-vertical-demo": {
      name: "volume-slider-control-vertical-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/volume-control.json","http://localhost:3000/r/styles/default/volume-state-control-demo.json"],
      files: [{
        path: "registry/default/examples/volume-slider-control-vertical-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-vertical-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-vertical-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-state-control-demo": {
      name: "volume-state-control-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/mute-control.json"],
      files: [{
        path: "registry/default/examples/volume-state-control-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-state-control-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-state-control-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "timeline-control-demo": {
      name: "timeline-control-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/timeline-control.json","http://localhost:3000/r/styles/default/timeline-labels.json"],
      files: [{
        path: "registry/default/examples/timeline-control-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/timeline-control-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timeline-control-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "timeline-labels-demo": {
      name: "timeline-labels-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/timeline-control.json","http://localhost:3000/r/styles/default/timeline-labels.json","http://localhost:3000/r/styles/default/use-timeline.json"],
      files: [{
        path: "registry/default/examples/timeline-labels-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/timeline-labels-demo.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timeline-labels-demo"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "linear-player": {
      name: "linear-player",
      description: "Modern seamless flat linear.app Media Player",
      type: "registry:block",
      registryDependencies: ["http://localhost:3000/r/styles/default/player-layout.json","http://localhost:3000/r/styles/default/media.json","http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/mute-control.json","http://localhost:3000/r/styles/default/player-hooks.json","http://localhost:3000/r/styles/default/playback-control.json","http://localhost:3000/r/styles/default/timeline-control.json","http://localhost:3000/r/styles/default/volume-control.json","http://localhost:3000/r/styles/default/use-timeline.json","http://localhost:3000/r/styles/default/use-volume.json","http://localhost:3000/r/styles/default/use-media-state.json","http://localhost:3000/r/styles/default/use-track-events.json","http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/create-media-store.json","http://localhost:3000/r/styles/default/fallback-poster.json","http://localhost:3000/r/styles/default/timeline-labels.json","http://localhost:3000/r/styles/default/use-shaka-player.json","http://localhost:3000/r/styles/default/limeplay-logo.json"],
      files: [{
        path: "registry/default/blocks/linear-player/media-player.tsx",
        type: "registry:component",
        target: "components/linear-player/media-player.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/volume-state-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/volume-state-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/playback-state-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/playback-state-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/volume-slider-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/volume-slider-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/timeline-slider-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/timeline-slider-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/bottom-controls.tsx",
        type: "registry:component",
        target: "components/linear-player/components/bottom-controls.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/media-element.tsx",
        type: "registry:component",
        target: "components/linear-player/components/media-element.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/player-hooks.tsx",
        type: "registry:component",
        target: "components/linear-player/components/player-hooks.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/button.tsx",
        type: "registry:ui",
        target: "components/ui/button.tsx"
      },{
        path: "registry/default/blocks/linear-player/lib/create-media-store.ts",
        type: "registry:lib",
        target: "components/linear-player/lib/create-media-store.ts"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/blocks/linear-player/media-player.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "linear-player"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
  }
}