/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["http://localhost:3000/r/styles/default/utils.json"],
      files: [],
      component: null,
      meta: undefined,
    },
    "mute-control": {
      name: "mute-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/use-volume-states.json"],
      files: [{
        path: "registry/default/ui/mute-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/mute-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "mute-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "media-provider": {
      name: "media-provider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/media-provider.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/media-provider.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "media-provider"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-layout": {
      name: "player-layout",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/use-player-root-store.json"],
      files: [{
        path: "registry/default/ui/player-layout.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/player-layout.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-layout"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "media": {
      name: "media",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/media.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/media.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "media"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-control": {
      name: "volume-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/volume-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/volume-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "playback-control": {
      name: "playback-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-media-state-states.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/ui/playback-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/playback-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "playback-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "player-hooks": {
      name: "player-hooks",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-shaka-player.json"],
      files: [{
        path: "registry/default/ui/player-hooks.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/player-hooks.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "player-hooks"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "timeline-control": {
      name: "timeline-control",
      description: "",
      type: "registry:ui",
      registryDependencies: ["http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json"],
      files: [{
        path: "registry/default/ui/timeline-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/timeline-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timeline-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/utils.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "create-media-store": {
      name: "create-media-store",
      description: "",
      type: "registry:lib",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json"],
      files: [{
        path: "registry/default/lib/create-media-store.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/create-media-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "create-media-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-player-root-store": {
      name: "use-player-root-store",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-player-root-store.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-player-root-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-player-root-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-volume-states": {
      name: "use-volume-states",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json"],
      files: [{
        path: "registry/default/hooks/use-volume-states.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-volume-states.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-volume-states"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-media-state-states": {
      name: "use-media-state-states",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/utils.json","http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-media-state-states.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-media-state-states.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-media-state-states"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-shaka-player": {
      name: "use-shaka-player",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-shaka-player.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-shaka-player.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-shaka-player"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-timeline-states": {
      name: "use-timeline-states",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/utils.json"],
      files: [{
        path: "registry/default/hooks/use-timeline-states.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-timeline-states.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-timeline-states"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-media-state-store": {
      name: "use-media-state-store",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json"],
      files: [{
        path: "registry/default/hooks/use-media-state-store.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-media-state-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-media-state-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-timeline-store": {
      name: "use-timeline-store",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json","http://localhost:3000/r/styles/default/utils.json"],
      files: [{
        path: "registry/default/hooks/use-timeline-store.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-timeline-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-timeline-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "use-volume-store": {
      name: "use-volume-store",
      description: "",
      type: "registry:hook",
      registryDependencies: ["http://localhost:3000/r/styles/default/use-player-root-store.json"],
      files: [{
        path: "registry/default/hooks/use-volume-store.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/hooks/use-volume-store.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-volume-store"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "playback-state-control": {
      name: "playback-state-control",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","button"],
      files: [{
        path: "registry/default/examples/playback-state-control.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/playback-state-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "playback-state-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-horizontal": {
      name: "volume-slider-control-horizontal",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/volume-state-control.json","http://localhost:3000/r/styles/default/volume-control.json"],
      files: [{
        path: "registry/default/examples/volume-slider-control-horizontal.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-horizontal.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-horizontal"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-vertical": {
      name: "volume-slider-control-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/volume-state-control.json","http://localhost:3000/r/styles/default/volume-control.json"],
      files: [{
        path: "registry/default/examples/volume-slider-control-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-vertical.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-vertical"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-state-control": {
      name: "volume-state-control",
      description: "",
      type: "registry:example",
      registryDependencies: ["http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/mute-control.json"],
      files: [{
        path: "registry/default/examples/volume-state-control.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-state-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-state-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "linear-player": {
      name: "linear-player",
      description: "Modern seamless flat linear.app Media Player",
      type: "registry:block",
      registryDependencies: ["http://localhost:3000/r/styles/default/player-layout.json","http://localhost:3000/r/styles/default/media.json","http://localhost:3000/r/styles/default/media-provider.json","http://localhost:3000/r/styles/default/mute-control.json","http://localhost:3000/r/styles/default/player-hooks.json","http://localhost:3000/r/styles/default/playback-control.json","http://localhost:3000/r/styles/default/timeline-control.json","button","http://localhost:3000/r/styles/default/volume-control.json","http://localhost:3000/r/styles/default/use-timeline-states.json","http://localhost:3000/r/styles/default/use-volume-store.json","http://localhost:3000/r/styles/default/use-timeline-store.json","http://localhost:3000/r/styles/default/use-media-state-store.json"],
      files: [{
        path: "registry/default/blocks/linear-player/media-player.tsx",
        type: "registry:component",
        target: "components/linear-player/media-player.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/volume-state-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/volume-state-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/playback-state-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/playback-state-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/volume-slider-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/volume-slider-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/timeline-slider-control.tsx",
        type: "registry:component",
        target: "components/linear-player/components/timeline-slider-control.tsx"
      },{
        path: "registry/default/blocks/linear-player/components/bottom-controls.tsx",
        type: "registry:component",
        target: "components/linear-player/components/bottom-controls.tsx"
      },{
        path: "registry/default/blocks/linear-player/lib/create-media-store.ts",
        type: "registry:lib",
        target: "components/linear-player/lib/create-media-store.ts"
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/blocks/linear-player/media-player.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "linear-player"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
  }
}