/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      component: null,
      meta: undefined,
    },
    "mute-control": {
      name: "mute-control",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/mute-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/ui/mute-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "mute-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/lib/utils.ts")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "playback-state-control": {
      name: "playback-state-control",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: [{
        path: "registry/default/examples/playback-state-control.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/playback-state-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "playback-state-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-horizontal": {
      name: "volume-slider-control-horizontal",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: [{
        path: "registry/default/examples/volume-slider-control-horizontal.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-horizontal.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-horizontal"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-slider-control-vertical": {
      name: "volume-slider-control-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: [{
        path: "registry/default/examples/volume-slider-control-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-slider-control-vertical.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-slider-control-vertical"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
    "volume-state-control": {
      name: "volume-state-control",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: [{
        path: "registry/default/examples/volume-state-control.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(async () => {
        const mod = await import("@/registry/default/examples/volume-state-control.tsx")
        const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "volume-state-control"
        return { default: mod.default || mod[exportName] }
      }),
      meta: undefined,
    },
  }
}