import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css"

import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {process.env.NODE_ENV === "development" && (
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      )}
      <body
        className={`${inter.className} dark bg-black antialiased`}
        data-theme="dark"
      >
        <main className="flex min-h-dvh w-full flex-col">{children}</main>
      </body>
    </html>
  );
}
